language: python

python:
  - "3.6"
  - "3.8"

cache: pip

install:
  - pip install -r requirements_test.txt

script:
  - python -m pytest --durations=5 --cov-report term --cov=. test/

after_success:
  - codecov
