language: python

python:
  - "3.6"
  - "3.8"

cache: pip

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov

install:
  - pip install -r requirements_test.txt

script:
  - python -m pytest --durations=5 --cov-report term --cov=. test/

after_success:
  - bash <(curl -s https://codecov.io/bash)
