os: linux
dist: xenial
language: python

python:
  - "3.6"
  - "3.8"

cache: pip

before_install:
  - python --version
  - python -m pip install --upgrade pip

install:
  - python -m pip install codecov -r requirements_test.txt

script:
  - python -m pytest --flake8 --durations=5 --cov-report term --cov=. .

after_success:
  - bash <(curl -s https://codecov.io/bash)
